projectmanager: fix upload of dsc files
Currently it's not possible to upload a dsc file to the project repository:

  $ elbe prjrepo upload_pkg <project> <dsc_file>
  [...]
  Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/elbepack/daemons/soap/faults.py", line 139, in wrapped
      return func(self, arg1, arg2, arg3)
    File "/usr/lib/python2.7/dist-packages/elbepack/daemons/soap/esoap.py", line 424, in include_package
      self.app.pm.add_deb_package(uid, filename)
    File "/usr/lib/python2.7/dist-packages/elbepack/projectmanager.py", line 506, in add_deb_package
      pkgname=pkg_name, force=True)
  TypeError: includedsc() got an unexpected keyword argument 'pkgname'

includedsc() doesn't have a pkgname parameter. Remove it.

Fixes: a02dfd19b303 ("projectmanager: allow add_deb_package() to add already existing pkg")
Signed-off-by: Kurt Kanzenbach <kurt@linutronix.de>
Signed-off-by: Manuel Traut <manut@linutronix.de>
Reviewed-by: Manuel Traut <manut@linutronix.de>