rfs.py: fix bug in inital run
directory needs to be created, before file can be written:

root@elbe-daemon:~# elbe buildchroot -t /opt/elbe/buildG -o buildG.log -n buildG
--skip-cdrom middleware-rfs.xml
Traceback (most recent call last):
  File "/usr/bin/elbe", line 58, in <module>
      cmdmod.run_command( sys.argv[2:] )
        File
  "/usr/lib/python2.7/dist-packages/elbepack/commands/buildchroot.py",
  line 161, in run_command
      buildenv = BuildEnv(xml, outf, chroot)
        File "/usr/lib/python2.7/dist-packages/elbepack/rfs.py", line 67,
        in __init__
            0755, "#!/bin/sh\nexit 101\n")
        File
        "/usr/lib/python2.7/dist-packages/elbepack/filesystem.py",
        line 96, in write_file
            f = self.open( path, "w" )
        File
        "/usr/lib/python2.7/dist-packages/elbepack/filesystem.py",
        line 42, in open
            return open( self.fname(path), mode )
            IOError: [Errno 2] No such file or directory:
            '/opt/elbe/buildG/chroot/usr/sbin/policy-rc.d'

Signed-off-by: Manuel Traut <manut@linutronix.de>