Revert "pkgutils: dont fallback to nonvirtapt code, when virtapt is avail"
This reverts commit 478b26e08550f1322ec2cb07db26d8fa961054b3.

The fallback code is used when creating the initvm from cdrom.
Removing the fallback broke initvm cration from cdrom.

multiprocessing.managers.RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 207, in handle_request
    result = func(c, *args, **kwds)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 386, in create
    obj = callable(*args, **kwds)
  File "/home/jogness/tmpfs/elbe/elbepack/virtapt.py", line 97, in __init__
    self.cache = apt_pkg.Cache()
Error: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The value 'jessie' is invalid for APT::Default-Release as such a release is not available in the sources
---------------------------------------------------------------------------

Signed-off-by: John Ogness <john.ogness@linutronix.de>
Signed-off-by: Manuel Traut <manut@linutronix.de>
Reviewed-by: Manuel Traut <manut@linutronix.de>