initvmaction: improve errormessages, when libvirt.open() fails
the following exception was seen, if entering the password to access
libvirt is delayed to long:

--------------------
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system reboot
[  325.635523] reboot: Restarting system
mkdir -p .stamps
touch .stamps/stamp-install-initial-image
libvirt: DBus Utils error : error from service: CheckAuthorization: Did not receive a reply. Possible causes include: the remote application did not send a
+reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/bin/elbe", line 55, in <module>
    cmdmod.run_command(sys.argv[2:])
  File "/usr/lib/python2.7/dist-packages/elbepack/commands/initvm.py", line 81, in run_command
    action = InitVMAction(args[0])
  File "/usr/lib/python2.7/dist-packages/elbepack/initvmaction.py", line 116, in __init__
    InitVMAction.__init__(self, node)
  File "/usr/lib/python2.7/dist-packages/elbepack/initvmaction.py", line 77, in __init__
    self.conn = libvirt.open("qemu:///system")
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 255, in open
    if ret is None:raise libvirtError('virConnectOpen() failed')
libvirt.libvirtError: error from service: CheckAuthorization: Did not receive a reply. Possible causes include: the remote application did not send a reply,
+the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Starting the initvm Failed
Giving up
--------------------

give a better message to the user.

Signed-off-by: Manuel Traut <manut@linutronix.de>
Reviewed-by: Troben Hohn <torben.hohn@linutronix.de>