fix typo
    elog.printo( "- package %s md5 %s does not match  installed md5 %s" % (name, md5,  pkg.installed.md5) )
AttributeError: 'APTPackage' object has no attribute
'installed'

needs to be pkg.installed_md5

Signed-off-by: Manuel Traut <manut@linutronix.de>