debian: add python3-distutils build dependency
needed to build for sid:

dh clean --with systemd --buildsystem=pybuild --with python2,python3
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:217: python2.7 setup.py clean
running clean
removing '/build/elbe-2.9.9+sid501/.pybuild/cpython2_2.7/build' (and everything under it)
'build/bdist.linux-amd64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
I: pybuild base:217: python3.6 setup.py clean
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from distutils.core import setup
ModuleNotFoundError: No module named 'distutils'
E: pybuild pybuild:330: clean: plugin distutils failed with: exit code=1: python3.6 setup.py clean
dh_auto_clean: pybuild --clean -i python{version} -p 3.6 returned exit code 13
make: *** [debian/rules:32: clean] Error 25

for stretch this is not needed:

'build/scripts-3.5' does not exist -- can't clean it
   debian/rules override_dh_clean
make[1]: Entering directory '/build/elbe-2.9.9+stretch501'
dh_clean
/usr/bin/make -j24 -C docs clean

because setup.py clean is not called for python3, probably a bug in the
older debhelper.

Signed-off-by: Manuel Traut <manut@linutronix.de>