initvm-submit: improve error handling if file doesn't exist
 % ./elbe initvm submit huhu.xml
elbe control create_project failed.
Traceback (most recent call last):
  File "/home/local/projects/elbe/elbe/elbe", line 58, in <module>
    mod = __import__(modname)
  File "/home/local/projects/elbe/elbe/elbepack/commands/control.py", line 30, in <module>
    from elbepack.soapclient import ClientAction, ElbeSoapClient
  File "/home/local/projects/elbe/elbe/elbepack/soapclient.py", line 159
    print ("%s doesn't exist" % filename file=sys.stderr)
                                            ^
SyntaxError: invalid syntax

Giving up

Signed-off-by: Manuel Traut <manut@linutronix.de>