licencexml: remove illegal chars from copyright before dom
after switching to the new lxml ElementTree, illegal chars
are not accepted in the nodes.

---------------------------------------------------------------
Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elbepack/asyncworker.py", line 116, in execute
    skip_pbuild=self.skip_pbuilder)
  File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 291, in build
    self.buildenv.rfs.write_licenses(f, self.log, os.path.join( self.builddir, "licence.xml"))
  File "/usr/lib/python2.7/dist-packages/elbepack/efilesystem.py", line 155, in write_licenses
    licence_xml.add_copyright_file (os.path.basename(dir), lic_text)
  File "/usr/lib/python2.7/dist-packages/elbepack/licencexml.py", line 64, in add_copyright_file
    txtnode.et.text = copyright
  File "lxml.etree.pyx", line 942, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:46397)
  File "apihelpers.pxi", line 684, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:20865)
  File "apihelpers.pxi", line 1393, in lxml.etree._utf8 (src/lxml/lxml.etree.c:27171)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
---------------------------------------------------------------

We just remove them, before adding the copyright string to the dom.