wsgi daemon: cast port to int
this should avoid:

  File "/usr/lib/python2.7/dist-packages/cherrypy/process/servers.py", line 187,
  in _start_http_thread
      self.httpserver.start()
        File
  "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py",
  line 1816, in start
      self.bind(af, socktype, proto)
        File
        "/usr/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py",
        line 1882, in bind
            self.socket.bind(self.bind_addr)
        File "/usr/lib/python2.7/socket.py", line 224, in meth
            return getattr(self._sock,name)(*args)
      TypeError: an integer is required

Signed-off-by: Manuel Traut <manut@linutronix.de>