packer: set default to use NoPacker instead of None
this fixes

--8<--
Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elbepack/asyncworker.py", line 158, in
execute
    skip_pbuild=self.skip_pbuilder)
  File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 598, in
build
    self.targetfs.pack_images(self.builddir)
  File "/usr/lib/python2.7/dist-packages/elbepack/efilesystem.py", line 373, in
pack_images
    packed = packer.pack_file(self.log, builddir, img)
AttributeError: 'NoneType' object has no attribute 'pack_file'

Exception:
'NoneType' object has no attribute 'pack_file'
--8<--

Signed-off-by: Manuel Traut <manut@linutronix.de>
Reviewed-by: Torben Hohn <torben.hohn@linutronix.de>