libvirt.xml.mako: use correct type for comments
the semi-automatic insertion of copyright statements added copyright
statements starting with '#' but in mako files '##' is needed.

this fixes the following message, that occurs during elbe initvm create

--8<--
libvirt: Domain Config error : (domain_definition):1: Start tag expected, '<' not found
^
Traceback (most recent call last):
  File "./elbe", line 55, in <module>
    cmdmod.run_command(sys.argv[2:])
  File "/home/local/projects/elbe/elbe/elbepack/commands/initvm.py", line 88, in run_command
    action.execute(directory, opt, args[1:])
  File "/home/local/projects/elbe/elbe/elbepack/initvmaction.py", line 338, in execute
    self.conn.defineXML(xml)
  File "/usr/lib/python2.7/dist-packages/libvirt.py", line 3677, in defineXML
    if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
libvirt.libvirtError: (domain_definition):1: Start tag expected, '<' not found
^
--8<--

Signed-off-by: Manuel Traut <manut@linutronix.de>