finetuning: decode() bytes from losetup in LosetupAction
get_command_out() returns bytes, resulting in:

-----------------------------------------------------------------------------------------------------
[CMD] mount "b'/dev/loop0'p1" "/var/cache/elbe/d7a3ac31-f4b3-442c-9ec5-f6f481fca7be/imagemnt"
mount: /var/cache/elbe/d7a3ac31-f4b3-442c-9ec5-f6f481fca7be/imagemnt: special device b'/dev/loop0'p1 does not exist.
[CMD] losetup --detach "b'/dev/loop0'"
losetup: b'/dev/loop0': failed to use device: No such device
[ERROR] ProjectFinetuning Error, trying to continue anyways
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/elbepack/finetuning.py", line 561, in execute_prj
    action.execute_img(buildenv, target, builddir, loop_dev)
  File "/usr/lib/python3/dist-packages/elbepack/finetuning.py", line 660, in execute_img
    with ImgMountFilesystem(img_mnt, device) as mnt_fs:
  File "/usr/lib/python3/dist-packages/elbepack/filesystem.py", line 524, in __enter__
    do(cmd)
  File "/usr/lib/python3/dist-packages/elbepack/shellhelper.py", line 258, in do
    raise CommandError(cmd, p.returncode)
elbepack.shellhelper.CommandError: Error: 32 returned from Command mount "b'/dev/loop0'p1" "/var/cache/elbe/d7a3ac31-f4b3-442c-9ec5-f6f481fca7be/imagemnt"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/elbepack/finetuning.py", line 773, in do_prj_finetuning
    action.execute_prj(buildenv, target, builddir)
  File "/usr/lib/python3/dist-packages/elbepack/finetuning.py", line 564, in execute_prj
    do(cmd)
  File "/usr/lib/python3/dist-packages/elbepack/shellhelper.py", line 258, in do
    raise CommandError(cmd, p.returncode)
elbepack.shellhelper.CommandError: Error: 1 returned from Command losetup --detach "b'/dev/loop0'"
------------------------------------------------------------------------------

Convert them to str using decode().

Signed-off-by: Torben Hohn <torben.hohn@linutronix.de>
Reviewed-by: Bastian Germann <bage@linutronix.de>