debathena-transform-lighttpd: remove line escapes, which are not supported
a .transform file does not support line escapes. it expects one filename
followed by sed commandlines.

------------------------------------------------------------------
Error: '/-e' does not contain '.debathena'
make: *** [debian/rules:4: binary] Error 2
------------------------------------------------------------------

remove the line escapes

Signed-off-by: Torben Hohn <torben.hohn@linutronix.de>
Acked-by: Sebastian Andrzej Siewior <bigeasy@linutronix.de>