debinstaller: move sig=urlopen() out of try: finally: block
when Release.gpg does not exist on the mirror, this backtrace is generated:

   File "/home/manut/Projects/elbe/elbe/elbe", line 55, in <module>
     cmdmod.run_command(sys.argv[2:])
   File "/home/manut/Projects/elbe/elbe/elbepack/commands/init.py", line 168, in run_command
     copy_kinitrd(xml.node("/initvm"), out_path)
   File "/home/manut/Projects/elbe/elbe/elbepack/debinstaller.py", line 231, in copy_kinitrd
     download_kinitrd(tmp, suite, mirror)
   File "/home/manut/Projects/elbe/elbe/elbepack/debinstaller.py", line 169, in download_kinitrd
     download_release(tmp, base_url)
   File "/home/manut/Projects/elbe/elbe/elbepack/debinstaller.py", line 157, in download_release
     sig.close()
 UnboundLocalError: local variable 'sig' referenced before assignment

move urlopen() out of the try: block. it did not catch the exception.
so the bahviour is not changed.

Signed-off-by: Torben Hohn <torben.hohn@linutronix.de>
Signed-off-by: Manuel Traut <manut@linutronix.de>
Reviewed-by: Manuel Traut <manut@linutronix.de>