elbeproject: set grub_fw_type when building wheezy project
The variable grub_fw_type didn't get set if the elbe project
was of type wheezy which resulted in a build failure
(github issue #156). Set grub_fw_type also in this missing case.

Command failed with errorcode 1
Build failed
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/elbepack/asyncworker.py", line 129, in execute
skip_pbuild=self.skip_pbuilder)
File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 489, in build
self.targetfs.part_target(self.builddir, grub_version, grub_fw_type)
UnboundLocalError: local variable 'grub_fw_type' referenced before assignment

Exception:
local variable 'grub_fw_type' referenced before assignment

Signed-off-by: Martin Kaistra <martin.kaistra@linutronix.de>
Signed-off-by: Manuel Traut <manut@linutronix.de>
Reviewed-by: Manuel Traut <manut@linutronix.de>