cdroms: dont crash when no <src-cdrom> node exists
normal xml files fail to create the source cdrom:

---------------------------------------------------------------------------
  File "/var/cache/elbe/devel/elbepack/asyncworker.py", line 181, in execute
    skip_pbuild=self.skip_pbuilder)
  File "/var/cache/elbe/devel/elbepack/elbeproject.py", line 625, in build
    self.build_cdroms(build_bin, build_sources, cdrom_size)
  File "/var/cache/elbe/devel/elbepack/elbeproject.py", line 469, in build_cdroms
    xml=self.xml)
  File "/var/cache/elbe/devel/elbepack/cdroms.py", line 97, in mk_source_cdrom
    for arch_vol in xml.node('src-cdrom').all('archive'):
AttributeError: 'NoneType' object has no attribute 'all'
Project build was not successful, current status: build_failed
---------------------------------------------------------------------------

dont try to access xml.node('src-cdrom'). Just use
xml.all('src-cdrom/archive') which will nicely iterate over nothing, if the
<src-cdrom> does not exist.

Signed-off-by: Torben Hohn <torben.hohn@linutronix.de>
Reviewed-by: John Ogness <john.ogness@linutronix.de>