elbe: kvm: added qemu-system-x86_64 as kvm executable
KVM has been merged into QEMU. The official way to use KVM these days is to use
'qemu-system-x86_64' with the '-enable-kvm' option. Thus, not all distributions
provide KVM wrappers. If there's no KVM wrapper script found, the Makefile
generation for the Init VM fails with an cryptic error message:

Traceback (most recent call last):
  File "/home/kurt/git/elbe/elbepack/templates.py", line 35, in template
    return Template(filename=fname,preprocessor=fix_linebreak_escapes).render(**d)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/kurt/git/elbe/elbepack/init/Makefile.mako", line 30, in render_body
    <%
ValueError: invalid literal for int() with base 10: 'v'

Thus, add qemu-system-x86_64 as KVM executable. If so, we need to make sure
that -enable-kvm is passed as option.

While here, removed unused code.

Signed-off-by: Kurt Kanzenbach <kurt@linutronix.de>
Signed-off-by: Manuel Traut <manut@linutronix.de>