Revert "sysroot: use packages by section instead of '-dev'"
This reverts commit dc5de49f00d34bb00ec1e7626eb86eaf4ac44d47.

Traceback (most recent call last):
  File "./elbe", line 61, in <module>
    cmdmod.run_command( sys.argv[2:] )
  File "/var/cache/elbe/elbepack/commands/buildsysroot.py", line 50, in run_command
    project.build_sysroot ()
  File "/var/cache/elbe/elbepack/elbeproject.py", line 133, in build_sysroot
    debootstrap_pkgs = [p.et.text for p in self.xml.node ("debootstrappkgs")]
TypeError: 'NoneType' object is not iterable