examples armhf-ti-beaglebone-black: fix artifact paths
Path generation for finetuning artifacts works using "target" + path.
However, when an artifact does not exist, this does not generate an
error. And so these 2 broken artifacts got ignored silently.

Except for the removal of "target/usr/lib/u-boot/am335x_boneblack/MLO"
in the project finetuning, which does not work, because the artifacts
name would have been "targetusr/lib/u-boot/am335x_boneblack/MLO".

-----------------------------------------------------------------------------------------------------
[ERROR] Finetuning Error
Trying to continue anyways
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elbepack/finetuning.py", line 728, in do_prj_finetuning
    action.execute_prj(buildenv, target, builddir)
  File "/usr/lib/python2.7/dist-packages/elbepack/finetuning.py", line 517, in execute_prj
    self.node.et.text)
FinetuningException: Artifact target/usr/lib/u-boot/am335x_boneblack/MLO doesn't exist
-----------------------------------------------------------------------------------------------------

Fix the paths, by prefixing with /

Signed-off-by: Torben Hohn <torben.hohn@linutronix.de>
Reviewed-by: John Ogness <john.ogness@linutronix.de>