Fix libvirt emulator qemu-kvm for x86_64
libvirt is looking for file "/usr/bin/qemu-system-x86_64 -enable-kvm".
See the following traceback:

----------------------------------------------------------------------
Traceback (most recent call last):
File "./elbe", line 55, in <module>
cmdmod.run_command(sys.argv[2:])
File "/home/olivier/linutronix/elbe/elbepack/commands/initvm.py", \
line 98, in run_command
action.execute(directory, opt, args[1:])
File "/home/olivier/linutronix/elbe/elbepack/initvmaction.py", \
line 560, in execute
self.conn.defineXML(xml)
File "/usr/lib/python3.8/site-packages/libvirt.py", line 3941, \
in defineXML
if ret is None:raise libvirtError('virDomainDefineXML() failed', \
conn=self)
libvirt.libvirtError: Cannot check QEMU binary \
/usr/bin/qemu-system-x86_64 -enable-kvm: No such file or directory
----------------------------------------------------------------------

In order to pass arguments to the emulator, 'find_kvm_exe()' returns a
dict with the informations about the qemu executable.  These
informations are then used in the 'libvirt.xml.mako' template to
generate the proper XML node.

Signed-off-by: Olivier Dion <dion@linutronix.de>
Tested-by: Bastian Germann <bage@linutronix.de>
Reviewed-by: Bastian Germann <bage@linutronix.de>
Signed-off-by: Torben Hohn <torben.hohn@linutronix.de>