esoap: call SimpleWSGISoapApp.__init__
needed, since we overloaded the constructor. it avoids:

    raise AssertionError("WSGI start_response called a second "
    AssertionError: WSGI start_response called a second time with no exc_info.

Signed-off-by: Manuel Traut <manut@linutronix.de>