Prevent UnicodeDecodeError on initvm creation
4643a4e8bf1("Python3: harmonize binary/unicode strings") introduced a bytes to
string conversion in elbepack.log that makes initvm creation throw a
UnicodeDecodeError (that is ignored) with Python 2.  Remove that conversion.

I successfully built some examples with Python 3 and it seems the former change
is unnecessary at this point.

The error stacktrace:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/bage/linutronix/elbe/elbe/elbepack/log.py", line 239, in
__call__
    self.run()
  File "/home/bage/linutronix/elbe/elbe/elbepack/log.py", line 263, in run
    self.lines[-1] += rest
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32:
ordinal not in range(128)
```

Signed-off-by: Bastian Germann <bage@linutronix.de>
Reviewed-by: Torben Hohn <torben.hohn@linutronix.de>