fix: partitions without a label may raise an exception
A partition tag without a label tag will cause the following exception:

    Build failed
    Traceback (most recent call last):
      File "/var/cache/elbe/devel/elbepack/asyncworker.py", line 112, in execute
        self.project.build(skip_pkglist=True, build_bin=self.build_bin, build_sources=self.build_src)
      File "/var/cache/elbe/devel/elbepack/elbeproject.py", line 301, in build
        self.targetfs.part_target( self.builddir, grub_version )
      File "/var/cache/elbe/devel/elbepack/efilesystem.py", line 298, in part_target
        self.images = do_hdimg( self.log, self.xml, targetdir, self, grub_version )
      File "/var/cache/elbe/devel/elbepack/hdimg.py", line 463, in do_hdimg
        img = do_image_hd( outf, i, fslabel, target, grub_version )
      File "/var/cache/elbe/devel/elbepack/hdimg.py", line 335, in do_image_hd
        if fslabel.has_key(part.text("label")) and fslabel[part.text("label")].fstype == "vfat":
      File "/var/cache/elbe/devel/elbepack/treeutils.py", line 41, in text
        raise Exception( "Cant find path %s" % path )
    Exception: Cant find path label

    Exception:
    Cant find path label

Now the schema enforces, that a label must be specified inside a partition tag.

Signed-off-by: Philipp Rosenberger <p.rosenberger@linutronix.de>