Revert "Python3: use encode instead of unicode() function"
This reverts commit 91b938d2491d2ae680b2165ec54fc73594bed874.
The "python3 fix" generates an Error on python2:

--------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/cache/elbe/devel/elbepack/asyncworker.py", line 186, in execute
    skip_pbuild=self.skip_pbuilder)
  File "/var/cache/elbe/devel/elbepack/elbeproject.py", line 585, in build
    self.buildenv.rfs.write_licenses(f, pkgnames, lic_xml_fname)
  File "/var/cache/elbe/devel/elbepack/efilesystem.py", line 161, in
    f.write(pkg.encode(encoding='utf-8', errors='replace'))
TypeError: write() argument 1 must be unicode, not str
--------------------------------------------------------------------------------------

This code only runs inside the initvm an does not need to be ported to
python3 immediately.

Revert until a proper resolution is found.

Signed-off-by: Torben Hohn <torben.hohn@linutronix.de>
Reviewed-by: Bastian Germann <bage@linutronix.de>