repomanager: fix key unlock for existing repo
the gnupg key should be unlocked by the repomanager constructor.
However "elbe prjrepo upload_pkg" fails with the following error:

--8<--
running cmd +reprepro --basedir
"/var/cache/elbe/e9c6c678-669b-4d6c-b822-d432e62a78ea/repo" export jessie+
------------------------------------------------------------------------------
gpgme gave error Pinentry:32870:  Inappropriate ioctl for device
ERROR: Could not finish exporting 'jessie'!
There have been errors!
------------------------------------------------------------------------------
Command failed with errorcode 251
--8<--

This is because the SignWith line in reprepos distribution configuration
was not parsed correctly. read_file returns a string an the loop iterates
over each character. But the code expects to iterate over lines.

While at it also improve the robustness of parsing the keyid. To allow
multiple whitespace between SignWith: and the keyid.

Signed-off-by: Manuel Traut <manut@linutronix.de>
Reviewed-by: Torben Hohn <torben.hohn@linutronix.de>