efilesystem: fix copy_filelist symlink to non existant directory copy
The example armel-rescue-busybox-cpio.xml triggers this bug:

----------------------------------------------------------------------------------------
[ERROR] Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/elbepack/asyncworker.py", line 186, in execute
    skip_pbuild=self.skip_pbuilder)
  File "/usr/lib/python2.7/dist-packages/elbepack/elbeproject.py", line 551, in build
    self.get_rpcaptcache())
  File "/usr/lib/python2.7/dist-packages/elbepack/efilesystem.py", line 83, in extract_target
    copy_filelist(src, file_list, dst)
  File "/usr/lib/python2.7/dist-packages/elbepack/efilesystem.py", line 40, in copy_filelist
    dst.fname(f)))
  File "/usr/lib/python2.7/dist-packages/elbepack/shellhelper.py", line 39, in system
    raise CommandError(cmd, ret)
CommandError: Error: 1 returned from Command cp -a --reflink=auto "/var/cache/elbe/d6bda8a8-fd79-4eba-a443-98ea0a8fefcb/chroot/bin/busybox" "/var/cache/elbe/d6bda8a8-fd79-4eba-a443-98ea0a8fefcb/target/bin/busybox"
Project build was not successful, current status: build_failed
elbe control wait_busy Failed
----------------------------------------------------------------------------------------

this is caused by /bin being a symlink to /usr bin.
The /bin symlink has already been copied at that point.
but /usr/bin has not.

Fix that by making sure, that the target directory of a symlink exists,
when its copied.

Signed-off-by: Torben Hohn <torben.hohn@linutronix.de>
Reviewed-by: Bastian Germann <bage@linutronix.de>