py3: debian - override tests
because some python packages are not available during buildtime testing
the code fails. This just overrides the default python test by a noop.
As soon as all python3 runtime dependencies are packaged in debian they
can be defined as build-dep and the tests can be reenabled.

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
I: pybuild base:184: cd /home/local/projects/elbe/elbe/.pybuild/pythonX.Y_3.6/build; python3.6 -m unittest discover -v
failed to import spyne
please install python(3)-spyne
elbepack.daemons.soap (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: elbepack.daemons.soap (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: elbepack.daemons.soap
Traceback (most recent call last):
  File "/home/local/projects/elbe/elbe/.pybuild/pythonX.Y_3.6/build/elbepack/daemons/soap/faults.py", line 24, in <modu
le>
    from spyne.model.fault import Fault
ModuleNotFoundError: No module named 'spyne'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/local/projects/elbe/elbe/.pybuild/pythonX.Y_3.6/build/elbepack/daemons/soap/__init__.py", line 23, in <module>
    from .esoap import ESoap
  File "/home/local/projects/elbe/elbe/.pybuild/pythonX.Y_3.6/build/elbepack/daemons/soap/esoap.py", line 35, in <module>
    from .faults import soap_faults
  File "/home/local/projects/elbe/elbe/.pybuild/pythonX.Y_3.6/build/elbepack/daemons/soap/faults.py", line 28, in <module>
    sys.exit(-20)
SystemExit: -20

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
E: pybuild pybuild:283: test: plugin distutils failed with: exit code=1: cd /home/local/projects/elbe/elbe/.pybuild/pythonX.Y_3.6/build; python3.6 -m unittest discover -v
dh_auto_test: pybuild --test -i python{version} -p 3.6 returned exit code 13
debian/rules:29: recipe for target 'build' failed
make: *** [build] Error 25

Signed-off-by: Manuel Traut <manut@linutronix.de>
Reviewed-by: Torben Hohn <torben.hohn@linutronix.de>