licencexml: Catch spurious exception
Getters of the cc variable can throw exceptions.  Thus, moved the list
of files creation in the try region.

Traceback:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/cache/elbe/devel/elbepack/asyncworker.py", line 194, in execute
    skip_pbuild=self.skip_pbuilder)
  File "/var/cache/elbe/devel/elbepack/elbeproject.py", line 654, in build
    [p.name for p in cache.get_installed_pkgs()])
  File "/var/cache/elbe/devel/elbepack/elbeproject.py", line 1052, in
gen_licenses
    env.rfs.write_licenses(f, pkg_list, lic_xml_fname)
  File "/var/cache/elbe/devel/elbepack/efilesystem.py", line 217, in
write_licenses
    licence_xml.add_copyright_file(pkg, lic_text)
  File "/var/cache/elbe/devel/elbepack/licencexml.py", line 82, in
add_copyright_file
    files.append((cc.files, cc.license.synopsis, cc.copyright))
  File "/usr/lib/python2.7/dist-packages/debian/deb822.py", line 2092,
in getter
    return field.from_str(val)
  File "/usr/lib/python2.7/dist-packages/debian/copyright.py", line 436,
in from_str
    lines = parse_multiline_as_lines(s)
  File "/usr/lib/python2.7/dist-packages/debian/copyright.py", line 408,
in parse_multiline_as_lines
    'continued line must begin with " "')
MachineReadableFormatError: continued line must begin with " "
----------------------------------------------------------------------

Reported-by: Bastian Germann <bage@linutronix.de>
Signed-off-by: Olivier Dion <dion@linutronix.de>
Reviewed-by: Bastian Germann <bage@linutronix.de>