debian: python3-elbe-bin: add python3-parted dependency
Add python3-parted as a runtime dependency since it is needed by
the "check_updates" command:

Traceback (most recent call last):
  File "/usr/bin/elbe", line 57, in <module>
    mod = __import__(modname)
  File "/usr/lib/python3/dist-packages/elbepack/commands/check_updates.py", line 12, in <module>
    from elbepack import virtapt
  File "/usr/lib/python3/dist-packages/elbepack/virtapt.py", line 22, in <module>
    from elbepack.rfs import create_apt_prefs
  File "/usr/lib/python3/dist-packages/elbepack/rfs.py", line 15, in <module>
    from elbepack.efilesystem import BuildImgFs
  File "/usr/lib/python3/dist-packages/elbepack/efilesystem.py", line 19, in <module>
    from elbepack.hdimg import do_hdimg
  File "/usr/lib/python3/dist-packages/elbepack/hdimg.py", line 13, in <module>
    import parted
ModuleNotFoundError: No module named 'parted'

Signed-off-by: John Ogness <john.ogness@linutronix.de>
Reviewed-by: Bastian Germann <bage@linutronix.de>