schema: drop duplicate partitition element
The partitions are already defined above.
It would make sense to restrict the layout to three primary partitions
when an extended partition is used. But the current schema does not
enforce this.

Fixes the following error from lxml:

```
elbe preprocess failed.
Traceback (most recent call last):
  File "/home/t-8ch/src/elbe/elbe", line 56, in <module>
    cmdmod.run_command(sys.argv[2:])
  File "/home/t-8ch/src/elbe/elbepack/commands/preprocess.py", line 46, in run_command
    xmlpreprocess(args[0], opt.output, variants, opt.proxy, opt.gzip)
  File "/home/t-8ch/src/elbe/elbepack/xmlpreprocess.py", line 316, in xmlpreprocess
    schema = etree.XMLSchema(schema_tree)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/xmlschema.pxi", line 89, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: complex type 'msdoshd': The content model is not determinist., line 1430
```

Signed-off-by: Thomas Weißschuh <thomas.weissschuh@linutronix.de>
Signed-off-by: Benedikt Spranger <b.spranger@linutronix.de>