commands: gen_update: fixed handling of pre/post.sh scripts
The current code throws an exception if the generation of update package
includes a pre and/or post shell script. Example:

root@elbe-daemon:# elbe gen_update -t . -p pre.sh -o test.pkg source.xml
[...]
Traceback (most recent call last):
  File "/usr/bin/elbe", line 61, in <module>
    cmdmod.run_command( sys.argv[2:] )
  File "/usr/lib/python2.7/dist-packages/elbepack/commands/gen_update.py", line 103, in run_command
    cfg_dir = opt.cfg_dir, cmd_dir = opt.cmd_dir )
  File "/usr/lib/python2.7/dist-packages/elbepack/updatepkg.py", line 136, in gen_update_pkg
    copyfile (project.presh_file, update + '/pre.sh')
  File "/usr/lib/python2.7/shutil.py", line 68, in copyfile
    if _samefile(src, dst):
  File "/usr/lib/python2.7/shutil.py", line 58, in _samefile
    return os.path.samefile(src, dst)
  File "/usr/lib/python2.7/posixpath.py", line 162, in samefile
    s1 = os.stat(f1)
TypeError: coercing to Unicode: need string or buffer, file found

The problem is, the code expects presh_file and postsh_file to be
strings. But they're file objects. So using strings fixes the issue.

Furthermore, adding a sanity check if the files actually exist and
printing a useful message to the user.

Signed-off-by: Kurt Kanzenbach <kurt@linutronix.de>
Signed-off-by: Manuel Traut <manut@linutronix.de>
Reviewed-by: Manuel Traut <manut@linutronix.de>