Change exception.message to str()
The 'message' attribute of an exception that inherit from
BaseException is not valid in Py3.  Thus, using the '__str__' method
of the exception instead to get the error message.

See the following traceback:

----------------------------------------------------------------------
Traceback (most recent call last):

File "/home/olivier/linutronix/elbe/elbepack/debinstaller.py", \
line 237, in copy_kinitrd
download_kinitrd(tmp, suite, mirror)
File "/home/olivier/linutronix/elbe/elbepack/debinstaller.py", \
line 175, in download_kinitrd
download_release(tmp, base_url)
File "/home/olivier/linutronix/elbe/elbepack/debinstaller.py", \
line 160, in download_release
raise InvalidSignature('Failed to verify Release file')
elbepack.debinstaller.InvalidSignature: Failed to verify Release file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/olivier/linutronix/elbe/elbe", line 55, in <module>
cmdmod.run_command(sys.argv[2:])
File "/home/olivier/linutronix/elbe/elbepack/commands/init.py", \
line 198, in run_command
copy_kinitrd(xml.node("/initvm"), out_path)
File "/home/olivier/linutronix/elbe/elbepack/debinstaller.py", \
line 251, in copy_kinitrd
raise NoKinitrdException('InvalidSignature %s' % e.message)
AttributeError: 'InvalidSignature' object has no attribute 'message'
----------------------------------------------------------------------

Signed-off-by: Olivier Dion <dion@linutronix.de>
Reviewed-by: Bastian Germann <bage@linutronix.de>
Signed-off-by: Torben Hohn <torben.hohn@linutronix.de>