elbe: shebang: force python2
Seems like Elbe is written in Python2. However, some distributions ship Python3
as default version. This results in errors like this:

  File "./elbe", line 29
    print 'elbe v' + elbe_version
                 ^
  SyntaxError: Missing parentheses in call to 'print'

So better force the used version to Python2.

Signed-off-by: Kurt Kanzenbach <kurt@linutronix.de>
Signed-off-by: Manuel Traut <manut@linutronix.de>